package secondPhase

import java.util.Random;
import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import com.sbz.battleship.domain.model.Ship;
import com.sbz.battleship.domain.model.Move;
import com.sbz.battleship.domain.model.Tuple;

import com.sbz.battleship.domain.model.enums.AgendaGroup;
import com.sbz.battleship.domain.model.enums.Strategy;
import com.sbz.battleship.domain.model.enums.Region;


import com.sbz.battleship.domain.model.decisions.MoveDecision;
import com.sbz.battleship.domain.model.decisions.AgendaGroupDecision;

import org.apache.commons.collections4.IterableUtils;





// TODO

// Kompletna strategy klasa moze u pravila...
// accumulate

// QUERY
// DRL funkcije
// kombinovanje pravila
